apiVersion: apps/v1
kind: Deployment
metadata:
  name: go-web-core
spec:
  selector:
    matchLabels:
      app: go-web-core
  template:
    metadata:
      labels:
        app: go-web-core
    spec:
      dnsPolicy: ClusterFirstWithHostNet
      hostNetwork: true
      containers:
        - name: zipkin
          image: openzipkin/zipkin:2.23
          ports:
            - name: zipkin
              containerPort: 9411
        - name: app
          image: go-web-core-amd64:1.0
          env:
            - name: APP_DB_HOST
              valueFrom:
                configMapKeyRef:
                  name: app-config
                  key: db_host
            - name: SALES_ZIPKIN_REPORTER_URI
              valueFrom:
                configMapKeyRef:
                  name: app-config
                  key: zipkin_reporter_uri
            - name: KUBERNETES_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
            - name: KUBERNETES_PODNAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: KUBERNETES_NAMESPACE_POD_IP
              valueFrom:
                fieldRef:
                  fieldPath: status.podIP
            - name: KUBERNETES_NODENAME
              valueFrom:
                fieldRef:
                  fieldPath: spec.nodeName
          ports:
            - name: app
              containerPort: 3000
            - name: app-debug
              containerPort: 4000
          readinessProbe:
            httpGet:
              path: /readiness
              port: 3000
            initialDelaySeconds: 30
            periodSeconds: 15
          livenessProbe:
            httpGet:
              path: /liveiness
              port: 3000
            initialDelaySeconds: 30
            periodSeconds: 15
---
apiVersion: v1
kind: Service
metadata:
  name: go-web-core
spec:
  selector:
    service: go-web-core
  ports:
    - name: zipkin
      port: 9411
      targetPort: zipkin
    - name: app
      port: 3000
      targetPort: app
    - name: app-debug
      port: 4000
      targetPort: app-debug
